from __future__ import annotations

import argparse
import sys
from pathlib import Path

from universal_rpa.application.workflow_codec import export_workflow_schema

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "docs" / "schemas" / "workflow-v1.schema.json"


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the workflow-v1 JSON Schema")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed schema bytes differ from generated bytes",
    )
    args = parser.parse_args()
    generated = export_workflow_schema()

    if args.check:
        if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_bytes() != generated:
            print(
                "workflow-v1.schema.json is out of date; run scripts/export_schema.py",
                file=sys.stderr,
            )
            return 1
        return 0

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = SCHEMA_PATH.with_suffix(".json.tmp")
    temporary_path.write_bytes(generated)
    temporary_path.replace(SCHEMA_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
